### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by tomauty** [dancormier/react-native-swipeout#100]
Hey, noticed there haven't been many updates since February of this year. If you're looking for a maintainer I wouldn't mind picking up some of the issues and PRs.

**Comment by braco** [comment]
@tomauty I'd be willing to help if you want to start a fork/new project.

**Comment by latusaki** [comment]
I don't think the original author is going to take part, I have released a fork as well, as I need to get going with RN 26.  Will also try to pick up the work for animated and transfer the PRs to my repo.. Although only got weekends for it.

**Comment by markrickert** [comment]
RN 27-rc looks like they added this functionality - https://github.com/facebook/react-native/commit/2a7f6aeda7544f8dec3455e607db472c0d08c197

Might be the nail in this project's coffin.

**Comment by latusaki** [comment]
I was looking at this earlier, although with no docs I wasnt sure of what exactly its doing!

**Comment by latusaki** [comment]
Yeah... looking at the code it looks like its this... Guess I dont need to spend more time with the animated view ✨

**Comment by dancormier** [comment]
Hey @tomauty, thanks for the suggestion.

It's true that life has intervened and made it difficult for me to devote time to this project. 

I've added you as a collaborator (as well @oblador and @mhollweck since they've both made healthy contributions to this project). The only thing I need is a periodic ping for any necessary npm updates.

**Comment by oblador** [comment]
Chipping in as I was mentioned. IMHO best is to deprecate this project with [SwipeableRow](https://github.com/facebook/react-native/tree/master/Libraries/Experimental/SwipeableRow) being actively developed in core.
