### ISSUE TITLE
Delete with autoClose causes warning "Can only update a mounted or mounting component"

### ISSUE THREAD

**Issue by kenfehling** [dancormier/react-native-swipeout#101]
When I use autoClose, upon deleting the item at the end of the list I get the warning:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Swipeout component.
`

but only when I delete the last item in the list.

I tried changing the items to use unique IDs instead of using the index (`rowID`) and this seemed to improve it somewhat, but it still happens with the last item in the list.

**Comment by kenfehling** [comment]
This PR appears to fix the issue: https://github.com/dancormier/react-native-swipeout/pull/102

**Comment by gitlovenotwar** [comment]
@kenfehling Do you have a working example on how to delete a row? with animation?
