### ISSUE TITLE
DC-Redux Touchable in Swipeout

### ISSUE THREAD

**Issue by latusaki** [dancormier/react-native-swipeout#105]
With the tweenstate implementation, the following works:

```
<Swipeout>
   <View>
      <TouchableHighlight/>
   </View>
</Swipeout>
```

Although on the Animated implementation, the swipe event is not triggered when a Touchable is in the contents (neither the touchable's onPress if its a drag). Anyone has solved this issue, or knows which is a good place to start resolving this?

**Comment by cupofjoakim** [comment]
@latusaki Any solution to this? I'm having the same issue

**Comment by latusaki** [comment]
I have switched to react-native-swipe-list-view.
ReactNative has an implementation for SwipeableList on current version, but it's not as good as above library *yet*

**Comment by cupofjoakim** [comment]
@latusaki thanks for the quick reply, much appreciated!
