### ISSUE TITLE
Plans for React Native 0.25+ support?

### ISSUE THREAD

**Issue by qpowell** [dancormier/react-native-swipeout#107]
In RN 26, `react-native-swipeout` throws an error when trying to evaluate React.createClass (in index.js) .  RN 25 changed the way that the React API needs to be required. Core React modules, like Component and PropTypes, are now required directly from `react`. Native-specific models, like Text and View, should be required from `react-native` (see https://github.com/facebook/react-native/releases/tag/v0.25.1). In RN 25, this is deprecated but its a breaking change in 0.26. 

Everything still works 100% in < 0.24, but I didn't see any issues so I figured I'd create this in case others run into the same problem.

Thanks :)

**Comment by magrinj** [comment]
You can use my fork #84, I'm waiting for merge!

**Comment by qpowell** [comment]
@magrinj Thanks! I also like your button changes.

**Comment by magrinj** [comment]
Your welcome! :)

**Comment by esutton** [comment]
@magrinj Thank you - I can keep working again with 0.26 ! 
```
  "dependencies": {
    "react": "15.0.2",
    "react-native": "^0.26.2",
    "react-native-swipeout": "git+https://github.com/magrinj/react-native-swipeout",
  }
```

**Comment by dozoisch** [comment]
@dancormier Anyway to get that merged :)? That'd be appreciated

**Comment by linoleum00** [comment]
@dancormier ::: Please merge @magrinj  PR!!!

**Comment by tomauty** [comment]
It is merged. Please pull from master branch until I have NPM access.
