### ISSUE TITLE
NPM Contributor

### ISSUE THREAD

**Issue by tomauty** [dancormier/react-native-swipeout#114]
Hey,

Would you mind adding me as an NPM contributor? I can push the RN0.25+ fixes as a new version.

**Comment by dieguitoweb** [comment]
+1

**Comment by silentcloud** [comment]
+1

**Comment by jsdevel** [comment]
@dancormier is there a reason you haven't responded to this?

**Comment by dancormier** [comment]
Hey all!

With a little nudging, I've finally added @tomauty as a maintainer to [react-native-swipeout](https://www.npmjs.com/package/react-native-swipeout)! Sorry for the delay! I've been devoted to a personal project and have been neglecting my swipeout responsibilities.

I'd also encourage everyone interested in this component to checkout **[React Native's own experimental work for a swipable row](https://github.com/facebook/react-native/tree/master/Libraries/Experimental/SwipeableRow)**

Thanks for the help and your patience everyone!
