### ISSUE TITLE
your release maybe a bit of a problem

### ISSUE THREAD

**Issue by MingYe-dz** [dancormier/react-native-swipeout#117]
your release maybe a bit of a problem, i must use git://github.com/dancormier/react-native-swipeout.git#master,then install the right 2.0.12

**Comment by Showyilu** [comment]
+1, having the same problem.

**Comment by silentcloud** [comment]
use this: https://www.npmjs.com/package/react-native-swipe-out

**Comment by silentcloud** [comment]
v2.0.13
