### ISSUE TITLE
Has this project the love that it needs?

### ISSUE THREAD

**Issue by flq** [dancormier/react-native-swipeout#128]
Hi there,
- 17 open pull requests
- 43 open issues for a single UI component
- last commit from July 1
- npm package from 7 months ago

I understand the strain of maintaining OSS, but also the need of react-antive devs building cool apps for such a component.

So, are there any forks around that are moving on with taking PRs etc.?

Regards

**Comment by jseminck** [comment]
Looks like no :( Even the current package on NPM doesn't work with the latest React Native version. But installing it straight from Github does. Would be nice to see any approach to make this move forward as the functionality that this package provides is very good! :)

**Comment by atdrago** [comment]
Like @jseminck, reference the git url in your package.json to make this work in the latest React Native version:

```json
{
  "dependencies": {
    "react-native-swipeout": "git://github.com/dancormier/react-native-swipeout.git"
  }
}
```

**Comment by silentcloud** [comment]
https://www.npmjs.com/package/react-native-swipe-out

**Comment by appsthatmatter** [comment]
@silentcloud please activate the issue tracker if you want to maintain it.

**Comment by JulianKingman** [comment]
@silentcloud I agree with @appsthatmatter , please activate issue tracker. Yours is clearly the most maintained, but not being able to track issues is a deal-breaker. There's also this repo, which *does* have an issue tracker: https://github.com/maintained-repos/react-native-swipeout

**Comment by silentcloud** [comment]
@appsthatmatter @JulianKingman done！

**Comment by ericwooley** [comment]
I emailed about @dancormier, hopefully he will add @silentcloud or someone else as a maintainer. Or deprecate in favor of @silentcloud s fork.

I know it's hard to maintain some of these projects, but at the same, this project solves a huge void for people. It would be great if it could be maintained, one way or another.

**Comment by dancormier** [comment]
Sorry for the inactivity everyone! I've been hard at work outside the RN world and let this component languish. My understanding a year ago or so was that RN was adding a swipable-row component, but I haven't kept up with the progress/status of that. So...

At @ericwooley's request, I added @silentcloud as a collaborator to this repo and as a maintainer on [npm](https://www.npmjs.com/package/react-native-swipeout). Hopefully, they can give this project some much-needed love.

**Comment by flq** [comment]
Well, I was more worried than anything else, so it's nice to see you are OK.

**Comment by silentcloud** [comment]
@dancormier Thanks, I will deprecate my fork later.
