### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by atlanteh** [dancormier/react-native-swipeout#131]
Hi,
when are you planning to update version and publish to npm? There are some important issues that we want and we can't take from npm, directly from github.
thx :)

**Comment by imclean** [comment]
Simply by updating the index to have this at the top would be a start:
import React from 'react';
var tweenState = require('react-tween-state')
import  {PanResponder, TouchableHighlight, StyleSheet, Text, View} from 'react-native';
var styles = require('./styles.js')

**Comment by blixten** [comment]
There is indeed a great need to update the npm package.

**Comment by silentcloud** [comment]
https://www.npmjs.com/package/react-native-swipe-out
