### ISSUE TITLE
Seem's like you're trying to access ReactNative.createClass...

### ISSUE THREAD

**Issue by caleb0** [dancormier/react-native-swipeout#138]
Yo,

Really want to use this component. However, I get this error when I try and compile:

![screen shot 2016-11-05 at 12 12 06 am](https://cloud.githubusercontent.com/assets/18242998/20013005/8bbdbd40-a2ec-11e6-95b1-9fbfc9c3b4b0.png)

Is there any fix? I am definitely importing React the right way.

**Comment by davidck** [comment]
Just ran into this too, using RN 0.36

**Comment by micchyboy1023** [comment]
Change your package.json to
"react-native-swipeout": "https://github.com/dancormier/react-native-swipeout.git"

For me, this worked.

**Comment by RailtonMatthew** [comment]
davidck's solution worked for me.

**Comment by davidck** [comment]
@RailtonMatthew I'd also suggest @micchyboy1023 's solution as if next update don't resolve this issue, you'll need to manually change it again.

**Comment by RailtonMatthew** [comment]
I tried @micchyboy1023 's solution first but it didn't work.  I've made a note to manually change if I have to rebuild. :)

**Comment by hungdev** [comment]
thank@micchyboy1023. 
It worked for me.

**Comment by ybing** [comment]
@micchyboy1023 thanks.
It worked for me.

**Comment by lvtanxi** [comment]
I met the same problem, how can I solve it

**Comment by sagivo** [comment]
thanks @micchyboy1023 it solved it for me.

**Comment by guns2410** [comment]
can this be pushed to npm as well

**Comment by ashik94vc** [comment]
Still occurring even after updating package.json

**Comment by caleb0** [comment]
@micchyboy1023 thanks!!
