### ISSUE TITLE
Text is wrapping on each character on newer versions of RN

### ISSUE THREAD

**Issue by lprhodes** [dancormier/react-native-swipeout#141]
Tried to fix in a fork but couldn't figure out a solution.

![untitled](https://cloud.githubusercontent.com/assets/162989/21044593/db113078-be50-11e6-8c1d-b7c2e669cc8e.png)

**Comment by silasl** [comment]
You can get around this issue by passing in a custom component for the button and applying styling to that. See the 'component' property.

**Comment by wordkarin** [comment]
I had this problem also, and used silasl's suggestion: 
instead of: 
`text: 'Delete'` 

I had to do: 
`component: <View style={styles.rowContainer}><Text style={styles.swipeText}>Delete</Text></View>
...
  rowContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeText: {
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold'
  },
`

**Comment by weiliank** [comment]
Works like a charm! @silasl and @wordkarin thank you!

**Comment by andrewnaeve** [comment]
Can we re-open this? This workaround is pretty inconvenient in my app, and I feel like its just a simple FlexBox error that is not intended to work like this.

**Comment by bighitbiker3** [comment]
@andrewnaeve you can use my fork if you'd like which has this bug fixed - https://github.com/bighitbiker3/react-native-swipeout
