### ISSUE TITLE
SwipeoutBtn: 'key' is not prop.

### ISSUE THREAD

**Issue by jaggerwang** [dancormier/react-native-swipeout#143]
### Description

Got warning message "SwipeoutBtn: 'key' is not prop. Trying to access it will result in ...".

### ENV

platform: iOS simulator
react-native-swipeout: newest
react-native: 0.39.2
react: 15.4.1

**Comment by DesignMonkey** [comment]
+1

**Comment by oleksii-pylypenko** [comment]
The problem is here:

`getDefaultProps: function() {
    return {
      backgroundColor: null,
      color: null,
      component: null,
      underlayColor: null,
      height: 0,
      key: null,
      onPress: null,
      disabled: false,
      text: 'Click me',
      type: '',
      width: 0,
    };
  },`

The **key** prop has a special meaning in React. It it is not passed to the component as prop but is used by React to aid the reconciliation of collections. https://facebook.github.io/react/docs/lists-and-keys.html#keys

**Comment by silentcloud** [comment]
I will fix this later, Thanks
