### ISSUE TITLE
Not compatible with React Native >0.40

### ISSUE THREAD

**Issue by praveenperera** [dancormier/react-native-swipeout#150]
I'm trying to use this with React Native 0.41.2 however I am getting the following error.

```
JSON value '({text = Edit;})' of type NSArray cannot be converted to NSNumber
```

http://imgur.com/a/vxLow

**Comment by MossP** [comment]
Have you assigned correctly? `{text:'Edit'}` rather than `{text:Edit}`

**Comment by stokesbga** [comment]
Yeah this thing is pretty old. I mean... 
```var React = require('react-native')```
I'll make some changes to support >0.40

**Comment by silentcloud** [comment]
@praveenperera Can you run project example correctly？I have already update react-native@0.41.2 for example.

**Comment by silentcloud** [comment]
If you have any problem, please reopen this issue
