### ISSUE TITLE
Is there a way to have images in the rows?

### ISSUE THREAD

**Issue by jeffmattson** [dancormier/react-native-swipeout#152]
Hello Dan,

I would like to put this over a listview that has images in the row.  When I tried to put an image in the view, I cannot see it in the rows.  Is there a way to make the row height larger?

Thanks!

**Comment by superandrew213** [comment]
I'm using images and it works. Show us some of your code.

**Comment by silentcloud** [comment]
Show some of your code, please.

**Comment by silentcloud** [comment]
If you still have problems, please reopen
