### ISSUE TITLE
auto close rows Swipe 

### ISSUE THREAD

**Issue by mgorabbani** [dancormier/react-native-swipeout#153]
How can i implement auto closing rows also removing?
like this [https://www.youtube.com/watch?v=JviAw7qnsys](url)

**Comment by moisesnandres** [comment]
I'm looking for that too

**Comment by silentcloud** [comment]
@mgorabbani You want `afterOpen` or `afterSwipe` property?

**Comment by mgorabbani** [comment]
when i swipe. if i swipe max the function will run. if i swipe little it will auto close. something like that.

**Comment by silentcloud** [comment]
@mgorabbani  https://github.com/dancormier/react-native-swipeout/commit/b5a225914228878e74ded6e45f907e3e790f868f

use `onOpen` and `onClose` props
