### ISSUE TITLE
Problems in ListView/ScrollView

### ISSUE THREAD

**Issue by lvcmenezes** [dancormier/react-native-swipeout#156]
I don't know if it only happens with me, but I think it is really hard to swipe a view that is inside of a list/scroll view component. It looks like the component doesn't know if I am trying to swipe or to scroll the container.

Do you guys have any fix for this issue?

**Comment by silentcloud** [comment]
@lvcmenezes  Please check the project example which uses `ListView` too.

**Comment by silentcloud** [comment]
If you still have problems， you can reopen this issue.
