### ISSUE TITLE
Touchable highlight works in simulator not on device

### ISSUE THREAD

**Issue by vTrip** [dancormier/react-native-swipeout#163]
I have a list of swipeout elements, the immediate child of <Swipeout> is a <TouchableHighlight> element which has a simply onPress function of navigating to a new page (i.e. Master > Detail).

Functionality works perfectly in simulator. 

Once deployed to real device, looks like the onPress event is cancelled out.

**Comment by stokesbga** [comment]
+1

**Comment by jbolter** [comment]
I'm having the same issue on my device. Works fine on the iOS simulator but onPress is not called for my TouchableHighlight that is a child of my Swipeout component.

**Comment by jbolter** [comment]
I'm wondering if this is related to this bug... https://github.com/facebook/react-native/issues/3082  I am using an iPhone 6S device for testing. I will try on another device and report back.

**Comment by birdwell** [comment]
I am having the same issue.

**Comment by vTrip** [comment]
**UPDATE** - I have moved to using SwipeRow library in conjunction with SwiplistView however. 

Reson being my swipe elements are not conventional swipe elements and found the above library to suit my needs better.

**Comment by jbolter** [comment]
Can this issue be re-opened? vTrip fixed the issue by switching to a different library.  However I found issues with SwipeRow and SwipeListView that brought me to this library.  The issue with TouchableHighlight is fixed in this fork of react-native-swipeout https://github.com/Shopify/react-native-swipeout so that is what I'm using for now but that is based upon an older version of this repository.  I would love to fix the issue in the current version of the code.

**Comment by noahhayes** [comment]
I'm running into this problem as well. Has anyone found a solution besides switching libraries completely?

**Comment by noahhayes** [comment]
I was able to resolve the issue just now by re-installing the npm package and then changing my import from 'rc-swipeout/lib' to 'react-native-swipeout'.

I'm not sure why it was looking at /lib to begin with. Perhaps it was older documentation.

**Comment by silentcloud** [comment]
@noahhayes try  react-native-swipeout@2.1.1

**Comment by kevando** [comment]
Thank you @silentcloud - I had the same issue as OP and using 2.1.1 fixed it for me.

```
npm uninstall react-native-swipeout
npm install react-native-swipeout@2.1.1
```
