### ISSUE TITLE
Close Event not always trigger

### ISSUE THREAD

**Issue by fbacker** [dancormier/react-native-swipeout#164]
issue:
onClose event doesn't always trigger and having stuff show/hide in the list based on that messes up. Example start draggning triggers onOpen but if you release on the way and it goes back, onClose is never triggered.
Also if open menu and click on button, the swipe is closed but no event.

fix:

_handlePanResponderEnd: around line 227 // close swipeout

    else {
        // close swipeout
        if (this.props.onClose) this.props.onClose();  <!-- add this
        this._tweenContent('contentPos', 0);
        this.setState({ contentPos: 0, openedLeft: false, openedRight: false, swiping: false });
      }

also around line 259

    _close: function() {
        if (this.props.onClose) this.props.onClose(); <!-- add this

**Comment by fbacker** [comment]
react-native-swipeout: 2.0.13

**Comment by silentcloud** [comment]
I will publish a new version later
