### ISSUE TITLE
Closing the swipeout causes an error

### ISSUE THREAD

**Issue by birdwell** [dancormier/react-native-swipeout#165]
Hello,

I can swipe and open the swipeout perfect. However, when I try to close the swipeout I get this error. I am unsure what would cause this. 

`
ExceptionsManager.js:71 View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flex: to flexGrow:) View: <RCTShadowView: 0x7fc59247ccc0; viewName: RCTView; reactTag: 567; frame: {{0, 0}, {0, 105}}>
`

**Comment by silentcloud** [comment]
please show the code

**Comment by birdwell** [comment]
It has to do with a container I have has a variable width of 95 the device. I'm extremely new to react native. I just need to find another way to make the style work. When I change the width to a fixed number it works fine.
