### ISSUE TITLE
3d touch screens not response to click

### ISSUE THREAD

**Issue by niros001** [dancormier/react-native-swipeout#166]
Hi, i use RN 0.44 and in iphone 6 the swipe work perfect but in iphone 6s (with 3d touch) only the swipe working but the list row cannot clickable (after some tests the row response to click only if i touch very very weak on the screen)

**Comment by AdamJNavarro** [comment]
I'm experiencing the same issue. Works as expected on my iPhone 6 but on the iPhone 7 the list item doesn't respond properly to touch. I'm running a fork of RN 0.42.

**Comment by atlanteh** [comment]
Happens to me too on android.
I even have a weirder problem. When building on a pc (running windows 10), everything works as expected on all the devices I checked, but when building using BuddyBuild, this issue happens on all of the devices. I tried it on multiple computers, tried wiping everything multiple times. still this scenario repeats itself.
I'm running RN 0.41.2

**Comment by wp2123** [comment]
Happens to me too.
It's very hard to trigger child's touch event on ip6s and ip7 while it's easy on ip6.
I'm running RN 0.43.3.

**Comment by silentcloud** [comment]
This will be fixed in version 2.0.14 later
