### ISSUE TITLE
Suggestion regarding button width

### ISSUE THREAD

**Issue by terencestone** [dancormier/react-native-swipeout#167]
Would be  great if you guys could add something like the following (widthSelector Prop) to allow some control over button width: 

![screen shot 2017-05-08 at 2 15 47 pm](https://cloud.githubusercontent.com/assets/19293584/25818639/44f65ca2-33f9-11e7-8e22-14e0a788def2.png)
![screen shot 2017-05-08 at 2 15 59 pm](https://cloud.githubusercontent.com/assets/19293584/25818641/49946b0a-33f9-11e7-838e-b81686402cfc.png)

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/issues/42
