### ISSUE TITLE
Restrict to open one swipe for a ListView

### ISSUE THREAD

**Issue by ugendrang** [dancormier/react-native-swipeout#168]
In ListView, currently swipe can be opened in mulitple rows. 

Is it possible to,
1. restrict to open only one swipe for a ListView
2. close all opened swipe when some other row is selected, so that ListView will have only one swipe open?

**Comment by binhnd-socicom** [comment]
@silentcloud I think the restriction should be implemented in your own list view instead of Swipeout view.

Implementing *onOpen* and *onClose* callbacks to update your state and update *close* attribute for each SwipeOut row would solve your problem.

**Comment by silentcloud** [comment]
yes, I agree with you
