### ISSUE TITLE
Warning: Failed prop type: Invalid prop on autoClose and sensitivity attributes

### ISSUE THREAD

**Issue by ugendrang** [dancormier/react-native-swipeout#170]
Warning: Failed prop type: Invalid prop `autoClose` of type `string` supplied to `Swipeout`, expected `boolean`.
    in Swipeout (created by StaticRenderer)

Warning: Failed prop type: Invalid prop `sensitivity` of type `string` supplied to `Swipeout`, expected `number`.
    in Swipeout (created by StaticRenderer)

`package.json
  "dependencies": {
    "react": "15.4.1",
    "react-native": "0.40.0",
    "react-native-store": "^0.4.1",
    "react-native-swipeout": "^2.0.13",
  },

\<Swipeout right={swipeBtns}
  autoClose='true'
  backgroundColor= 'transparent'
  sensitivity = '20'
  \>`

**Comment by silentcloud** [comment]
@ugendrang 

```js

<Swipeout right={swipeBtns}
autoClose
backgroundColor= 'transparent'
sensitivity={20}
>
```
