### ISSUE TITLE
swipout's child view can't response onPress envent in android system

### ISSUE THREAD

**Issue by solitaire12** [dancormier/react-native-swipeout#171]
swipout's child view can't response onPress envent in android system,but it's ok in ios

<Swipeout>
      <CartItem onPress={()=>{doSomething}}/> // do not work in android but it's ok in ios
</Swipeout>

**Comment by silentcloud** [comment]
try version 2.1.1 @solitaire12 , if you have any problems, please reopen issue

**Comment by benevbright** [comment]
I just published extension of Swipeout to make it works like Android behavior on Android. 
Try this.
https://www.npmjs.com/package/react-native-swipeout-longpressforandroid
