### ISSUE TITLE
gesture can't work with <TouchableOpacity/>

### ISSUE THREAD

**Issue by Yohann-Chen** [dancormier/react-native-swipeout#172]
like this:
```
<TouchableOpacity onPress={()=>this.cellDidPress}>
<Swipeout 
         autoClose={true}
         backgroundColor={'white'}
         right={this.state.Rightbuttons}
    >
       <Text>This is a Test</Text>
</Swipeout>
</TouchableOpacity>
```

the TouchableOpacity is failure, onPress method can't word
but the swipe gesture can use.
Is mean Father component used TouchableOpacity, the son component use Swipeout, TouchableOpacity will fail
Looking forward to your reply.thanks

**Comment by silentcloud** [comment]
@Yohann-Chen  try like this:

```js
<Swipeout 
         autoClose={true}
         backgroundColor={'white'}
         right={this.state.Rightbuttons}
    >
<TouchableOpacity onPress={()=>this.cellDidPress}>
       <Text>This is a Test</Text>
</TouchableOpacity>
</Swipeout>
```

**Comment by sonner911** [comment]
The obvious problem is how you call your method:
`<TouchableOpacity onPress={()=>this.cellDidPress}>`
I think you should do this:
`<TouchableOpacity onPress={()=>this.cellDidPress()}>`

**Comment by kivannc** [comment]
I have the same problem too. It works sometimes but when I remove Swipeout it works every time as expected. But when swipeout is added it behaves weird. 
```
        return (
            <Swipeout
                sensitivity={300}
                right={swipeBtns}
                autoClose
                backgroundColor='transparent'
            >
                <TouchableOpacity onPress={this.onPressRow.bind(this, rowData)}>
                    <View>
                        <View style={styles.headerStyle}>
                            <Text style={styles.rowText}>{rowData.catalog && rowData.catalog.title ? rowData.catalog.title : ''}</Text>
                            <Text style={styles.rowText}>{rowData.kilogram} </Text>
                            <Text style={styles.rowText}>{rowData.unit}</Text>
                            <Text style={styles.rowText}>{rowData.averageSection}</Text>
                        </View>
                        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>

                        </View>
                    </View>

                </TouchableOpacity>
            </Swipeout>
        );
```

**Comment by silentcloud** [comment]
@kivannc  `onPress={() => this.onPressRow.bind(this, rowData)}`

**Comment by m-vdb** [comment]
Inverting the two works 100% of the time for me, i.e. putting the `<TouchableOpacity>` inside the `<Swipeout>` component.

**Comment by kivannc** [comment]
I have still have the same issue I don't know what is the problem. I am testing on android 4.4.4

**Comment by MatthieuPeyrot** [comment]
Hi i have the same issue.
i have a TouchableOpacity inside the Swipeout who is inside a flat list 
On iOS it works perfectly but on android i have to use two finger to swipe.
