### ISSUE TITLE
Show icon

### ISSUE THREAD

**Issue by RailtonMatthew** [dancormier/react-native-swipeout#177]
Hi, is it possible to show an icon instead of (or as well as) the text for Android?

Like the iPhone mail app. 

Thanks.

**Comment by silentcloud** [comment]
You can pass customized component to button, see https://github.com/dancormier/react-native-swipeout#button-props

**Comment by RailtonMatthew** [comment]
Thanks, can you provide an example?  I'm new to react-native so still learning. :)

**Comment by ignivaravinderrikhi** [comment]
@RailtonMatthew  If you are still working on it 
You can check this code if you are trying to embed components as buttons In your swiper... 

import React, { Component } from 'react';
import {
    StyleSheet,
    View,
    Dimensions,
    Image,
    Text,
    TouchableOpacity,
    FlatList
} from 'react-native';

import Swipeout from 'react-native-swipeout';

let screen = Dimensions.get('window');

export default class Notifications extends Component {
  state = {
    listLength:0,
    notificationList:[{
      _id:1
    },{
      _id:2
    },{
      _id:3
    }]
  };

  renderRow(rowData) {
    let context = this,
    btnsComponent = [
      {
        component:
        <TouchableOpacity style={[styles.accepRejectButton,{backgroundColor:'#F18230'}]}>
          <View>
            <Text style={{color:'white'}}>
              Accept
            </Text>
          </View>
        </TouchableOpacity>
      },
      {
        component:
        <TouchableOpacity style={[styles.accepRejectButton,{backgroundColor:'#2B2B2B'}]}>
          <View>
            <Text style={{color:'white'}}>
              Reject
            </Text>
          </View>
        </TouchableOpacity>
      }
    ]

    return (
      <View>
        <Swipeout right={btnsComponent} style={{backgroundColor:'transparent'}}>
          <View style={[styles.swiperViewStyle]}>
            <Text>
              Swipe me left
            </Text>
          </View>
        </Swipeout>
      </View>
    )
  }

  render(){

    let context = this;
    const { navigate } = context.props.navigation;

    return (
      <View style={{flex:1}}>
        <View style={{flex:1}}>
        {
          (context.state.notificationList.length > 0) ?
            <FlatList data={context.state.notificationList} renderItem={context.renderRow} horizontal={false} keyExtractor={(item,index) => item._id}/>
            :
            <View style={{flex:1,justifyContent:'center',alignItems:'center'}}>
              <Text>
                No New Data to list
              </Text>
            </View>
        }
        </View>
      </View>
    )
  }

}

const styles = StyleSheet.create({
  swiperViewStyle:{
    height:(screen.height/10),
    paddingHorizontal:(screen.width/20),
    borderBottomWidth:0.2,
    justifyContent:'center'
  },
  accepRejectButton:{
    height:(screen.height/10),
    alignItems:'center',
    justifyContent:'center'
  }
});

**Comment by RailtonMatthew** [comment]
Thanks ignivaravinderrikhi for the response.  I did actually manage to work out how to do it, and I should have updated the thread!

My approach was different to yours.  I created an icons component because I have the same need in multiple .js files.  

icons.js

```
'use strict';

import React, { Component,PropTypes } from 'react';
import {  AppRegistry,  Image,  Navigator,  StyleSheet,  ScrollView,	TouchableOpacity,  Text,  View } from 'react-native';
import Entypo from 'react-native-vector-icons/Entypo';

class PCIcon extends Component {
    constructor(props) {
      super(props)
    }
	  render = () => {
    if (this.props.name == 'plus_minus') {
			return (
				<View style={{flex: 1,flexDirection: 'row',alignItems: 'center',justifyContent: 'center'}}>
					<Entypo {...this.props}
						name='plus'
						color={this.props.colour}
						size={this.props.size || 24 }/>
					<Entypo {...this.props}
						name='minus'
						color={this.props.colour}
						size={this.props.size || 24 }/>
					</View>
			);
		}
		else {
			return (
				<View style={{flex: 1,flexDirection: 'column',alignItems: 'center',justifyContent: 'center'}}>
					<Entypo {...this.props}
						name={this.props.name}
						color={this.props.colour}
						size={this.props.size || 30 }/>
				</View>
			);
		}
	}
}

export default PCIcon;

```
main.js (only relevant code shown)

```
import PCIcon from './icons';

Render() {

buttons.push({text: 'Copy', component: this.icon('copy','white'), onPress: function() {self.pcCopy(data)}});

return (
        <Swipeout
          key={data.id}
          autoClose={true}
          right={buttons}
          >
</Swipeout> )
}

icon(iconName,iconColour) {
    return ( <PCIcon name={iconName} colour={iconColour}/> )
}


```
