### ISSUE TITLE
Any suggestions to close the swipeouts when tabbing other conponents ?

### ISSUE THREAD

**Issue by ekkapob** [dancormier/react-native-swipeout#18]
I am making a page alike IOS Phone - Favorites when you can swipe left for actions and auto-close the swipeouts when tabbing other components or change tab view

**Comment by dancormier** [comment]
I have not yet implemented a way to close swipeouts based on parent, but I plan to work on it tomorrow.
My solution to #5 and #12 should hopefully be a fix for your problem.

**Comment by dancormier** [comment]
In commit e96aaea21f06921f7a6d14bff2beec84ec93f8dd, I added functionality to close open swipeouts when initiating a swipeout.
