### ISSUE TITLE
Swiping causes button text to wrap

### ISSUE THREAD

**Issue by joshfarrant** [dancormier/react-native-swipeout#180]
I've just wrapped a component in swipeout and, while it's mostly perfect, the one thing I have noticed is that the text wraps mid swipe.

![image](https://user-images.githubusercontent.com/6840861/26983523-f92e5e6a-4d33-11e7-8006-b266278bca1e.png)

In this case, I'm about half way through my swipe to the left and the text is wrapping on to two lines. It also wraps to three or more lines, depending on the length of the text and how wide the container is. I'm guessing this isn't expected, as the demo gifs don't show this.

Any thoughts on how to prevent the text wrapping?

**Comment by p-ugulino** [comment]
Hey,

I had the same problem and also my list was lagging a bit. 

So, instead of doing this:
`{
    text: 'Edit',
    backgroundColor: '#f39c12',
    color: 'white',
    underlayColor: '#e67e22',
  },`
I started doing this:
`{
    text: 'Edit',
    backgroundColor: '#f39c12',
    color: 'white',
    component: <Text>Edit</Text>,
    underlayColor: '#e67e22',
  },`

With that I solved my lagging and the text wrapping.

**Comment by ethanyanjiali** [comment]
It is also troubling me

**Comment by ethanyanjiali** [comment]
My workaround is this:

```
const swipeBtns = [
       {
          component: <Text style={{numberOfLines: 1}}>Edit</Text>,
        },
]
```

**Comment by whatlife** [comment]
it's work for me! @p-ugulino
