### ISSUE TITLE
0.44版本之后，这个三方就不能用了么？

### ISSUE THREAD

**Issue by jianjiandandan** [dancormier/react-native-swipeout#186]
我升级版本到0.44.3之后，就开始报错了，是不能用还是我写的方法不对，0.42还是没有任何问题的

**Comment by MataHu** [comment]
+1

**Comment by arniu** [comment]
@jianjiandandan  我也遇到类似的问题。

原因是 RN 0.44.3 引入新组件 `ViewPropTypes` 而移除了 `View.propTypes`， RN 升级之后找不到 `View.propTypes` 就开始报错。把该组件升级到 2.2.0 就可以了，具体可参考 #201 。

而我的情况恰恰相反，RN 是 0.40，而该组件升级到 2.2.0 之后反倒开始报错。

**Comment by silentcloud** [comment]
v 2.2.2
