### ISSUE TITLE
Text in buttons wraps when component is opened

### ISSUE THREAD

**Issue by cubabit** [dancormier/react-native-swipeout#187]
The text inside the buttons of the open component wraps while the component is being opened.

i.e. if the buttons are only 10 pixels wide while being swiped, then the text wraps single characters at a time to fit in the space.

I have observed this in the example included in the library too. This means it does not behave like the gif animation in the README file

Using react native 0.41.2

**Comment by silentcloud** [comment]
Please search  before submitting a new issue, thanks 

https://github.com/dancormier/react-native-swipeout/issues?utf8=%E2%9C%93&q=wrap

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/pull/183

**Comment by cubabit** [comment]
Apologies!
