### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by whatlife** [dancormier/react-native-swipeout#188]
![qq](https://user-images.githubusercontent.com/18432170/27617416-be323138-5be8-11e7-89af-c9ad309994eb.png)

see above, somebody help me?
I can run project example successfully.

**Comment by silentcloud** [comment]
Please show your code.

It seems that you pass a wrong property type to `ellipsizeMode`

**Comment by n4bcak3** [comment]
@whatlife 
Got the same error: problem in this component
https://github.com/dancormier/react-native-swipeout/blob/master/NativeButton.js#L61

and `clip` is working only for iOS

**Comment by silentcloud** [comment]
@n4bcak3 @whatlife Sorry about this, this pr https://github.com/dancormier/react-native-swipeout/pull/183/files caused the problem.

I will fix this soon.

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/commit/533b307d359d797d86cae88269b77fb00ada23cb

version: 2.1.3

**Comment by kmcrawford** [comment]
Setting the `ellipsizeMode` fixes the below issue.  I suggest the following:

`ellipsizeMode={Platform.OS ==='ios' ? 'clip' : 'tail'}`

This will fix issue on iOS and perform the default for Android.
https://facebook.github.io/react-native/docs/text.html

Without the clip (and Android behavior)
![screenshot_1508325800](https://user-images.githubusercontent.com/40531/31716384-7c3e5d0c-b3d5-11e7-873f-7d5d68e4762a.png)

With the clip on iOS
![simulator screen shot - iphone 8 - 2017-10-18 at 07 23 27](https://user-images.githubusercontent.com/40531/31716387-7ed0497c-b3d5-11e7-968e-ff0e41e50070.png)

**Comment by silentcloud** [comment]
@kmcrawford Hope for your PR
