### ISSUE TITLE
New feature: tap to open

### ISSUE THREAD

**Issue by SudoPlz** [dancormier/react-native-swipeout#194]
Hi,
I was wondering if that feature already exists (I didn't really find it).

Is there a way to enable tap to open (while keeping the swipe to open functionality) ?

Thanks

**Comment by silentcloud** [comment]
@SudoPlz use state to change `close` prop

**Comment by SudoPlz** [comment]
Roger that, cool!

**Comment by CandyOgre** [comment]
@silentcloud @SudoPlz How you do it? I can`t open swipeout if just changing `close` prop

**Comment by SudoPlz** [comment]
@CandyOgre I didn't implement that after all, I wish I could help more.

**Comment by CandyOgre** [comment]
@SudoPlz @silentcloud I made a fork and it`s working now: https://github.com/CandyOgre/react-native-swipeout

**Comment by silentcloud** [comment]
Only support `swipe to close` and `tap to close`
