### ISSUE TITLE
Missing react-import in latest release

### ISSUE THREAD

**Issue by daniel-lundin** [dancormier/react-native-swipeout#195]
In the latest release the import of React in NativeButtons.js was removed.
It is still needed for the JSX-tags, so right now render crashes with
"React is not defined"

**Comment by ericvillemure** [comment]
Will there be a new release soon for this fix or should I use a previous version?

**Comment by pietro909** [comment]
I apologize, I think my PR broke it.

I'd like to add some tests to be sure anyone can work on this repo without breaking it.
