### ISSUE TITLE
cant find variable React

### ISSUE THREAD

**Issue by armnotstrong** [dancormier/react-native-swipeout#199]
Hey,

   I want to use this plugin in my project like this:

```
import Swipeout from 'react-native-swipeout'
import React,{Component,PureComponent} from 'react';
import { Alert, Button,AppRegistry,FlatList, StyleSheet, ScrollView,Text, View,Image,TextInput } from 'react-native';
import {StackNavigator} from 'react-navigation'
import myData from './data.json'


class MyListItem extends PureComponent {

  render(){
      //var Swipeout = require('react-native-swipeout')
    return (


        <Swipeout right={[
            {
                text: 'Button'
            }
        ]}>
          <View style={styles.detailCard}>


              <Text style={styles.detailCardContent}>{this.props.content}</Text>

              <View
                  style={{
                      borderBottomColor: '#e8edeb',
                      borderBottomWidth: 1,
                  }}
              />

              <Text style={styles.detailCardRefContent} > {this.props.re}</Text>

              </View>
        </Swipeout>
      );
  }

}
```

But when it rendered it gives an error like this:

`can't find variable React`

![wechatimg41](https://user-images.githubusercontent.com/3839691/28492497-859080de-6f37-11e7-9b4c-9b539bd66cd4.jpeg)

As a newbie I don't know what to do to make this work, I install the plugin via 

`npm install --save react-native-swipeout`

And took the sample code as an instruction.

And further more, I also don't know where to define the `right` attribute as a variable so I just hard code it there

**Comment by jkingworking** [comment]
There's a pull request in to fix this issue.
You can see the fix here https://github.com/dancormier/react-native-swipeout/pull/196/files
All you need to do in the short term until this is merged is just add the import statement to the top of the node_modules/react-native-swipeout/NativeButton.js file. 
or
Roll back and use "2.1.3" of this module

**Comment by armnotstrong** [comment]
Thanks, that fixed my problem

**Comment by silentcloud** [comment]
sorry about this, please use version `2.1.5`
