### ISSUE TITLE
add style support for button

### ISSUE THREAD

**Issue by armnotstrong** [dancormier/react-native-swipeout#200]
Hi, 

It will be great if there is support of style control of buttons (like `margin` `padding`)

So that I could make the swiped card same height with the original one since I use `padding` for the original card

![wechatimg42](https://user-images.githubusercontent.com/3839691/28495909-ed07259e-6f8f-11e7-9607-7a7b72706fb7.jpeg)

**Comment by frontvu** [comment]
You can do this by specifying a `component` prop vs using the tradition `primary` button etc.
