### ISSUE TITLE
Slider animation bug when cursor is focused in a text box

### ISSUE THREAD

**Issue by kristinelson** [dancormier/react-native-swipeout#205]
The swipeout freaks out. I tried to include screenshots below of what the user sees step-by-step when a user tries to do this in their cart. This is in our iOS app while using react native. 

Steps to reproduce:

* Slide a cart item from right to left to display the delete button
* Click into the promo text box (this puts the cursor focus in a different area of the screen)
* Then try to slide the cart item again

If you have any additional questions, please let me know: kristi@transisland.tech

<img width="1012" alt="swipeout_bug" src="https://user-images.githubusercontent.com/16325590/28839497-decc49bc-76c1-11e7-9110-dfd97cedb923.png">

**Comment by silentcloud** [comment]
@kristinelson You want to use `swipeout` with `TextInput` ?

**Comment by kristinelson** [comment]
Looks like we dug more into it and found the issue. Thanks for your speedy response @silentcloud!
