### ISSUE TITLE
the props of close doesn't work! 

### ISSUE THREAD

**Issue by huanghaodong** [dancormier/react-native-swipeout#212]
import React,{Component} from 'react';
import {
  AppRegistry,
  AsyncStorage,
  Button,
  StyleSheet,
  Text,
  View,
  ListView,
  TouchableWithoutFeedback
} from 'react-native';
import Swipeout from 'react-native-swipeout';
const rows = [1,2,3,4,5,6,7,8,9];
class deleteMe extends Component {

  constructor() {
    super();
    var ds = new ListView.DataSource({rowHasChanged: (row1, row2) => true});

    this.state = {
      dataSource: ds.cloneWithRows(rows),
      rowID: null,
      sectionID:null
    };
  }

  _renderRow(rowData, sectionID, rowID) {
    return (
      <Swipeout
        close={!(this.state.sectionID === sectionID && this.state.rowID === rowID)}
        right={[{text:'button'}]}
        rowID={rowID}
        sectionID={sectionID}
        autoClose={true}
        backgroundColor={'#fff'}
        onOpen={(sectionID,rowID) => {
          this.setState({
            rowID,
            sectionID
          })
        }}
      >
        <TouchableWithoutFeedback onPress={() => console.log('press children')}>
            <View style={styles.li} >
               <Text>{rowData}</Text>
            </View>
        </TouchableWithoutFeedback>
      </Swipeout>
      );
  }

  render() {
    return (
      <View style={styles.container}>
        <ListView
           dataSource={this.state.dataSource}
          renderRow={this._renderRow.bind(this)}
        />
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container:{
    backgroundColor:'#fff',
    flex:1
  },
  li:{
    height:60,
    borderColor:'#000',
    borderBottomWidth:1
  }
})
AppRegistry.registerComponent('deleteMe', () => deleteMe);

**Comment by silentcloud** [comment]
check the https://github.com/dancormier/react-native-swipeout/blob/master/example/SwipeoutExample.js

**Comment by huanghaodong** [comment]
My demo is like yours,but the props of Close doesn't work.

**Comment by wanderSX** [comment]
Yep, also doesn't work for me

**Comment by olejka91** [comment]
@huanghaodong Have you found out the workaround?
