### ISSUE TITLE
请问侧滑滑动出的按钮，监听事件是怎么处理的啊

### ISSUE THREAD

**Issue by HeartSea** [dancormier/react-native-swipeout#213]

**Comment by silentcloud** [comment]
没明白你的意思 @HeartSea

**Comment by HeartSea** [comment]
@silentcloud 就是右侧滑出来的删除按钮的监听事件。。。。

**Comment by silentcloud** [comment]
@HeartSea 你不看文档的么？

https://github.com/dancormier/react-native-swipeout#button-props
