### ISSUE TITLE
Have both onPress and Swipe handlers in an element

### ISSUE THREAD

**Issue by shadrech** [dancormier/react-native-swipeout#215]
I have a list where I need to both have the swipe element to delete the list item, but also I need the item to have a onPress handler. So far I've tried implementing this with a TouchableHighlight parent:

```
<TouchableHighlight onPress={() => console.log("hello")}>
  <Swipeout right={rightButtons} autoClose={true}>
    ...
  </Swipeout>
</TouchableHighlight>
```

Problem is swipe works, but the TouchableHighlight doesn't pick up press events anymore. Is there a way to have both the click handler and swipe handler?
@dancormier @cancan101 @iwater @oblador @daniel-lundin

**Comment by shadrech** [comment]
@dancormier @cancan101 @iwater @oblador @daniel-lundin

**Comment by silentcloud** [comment]
@shadrech please check the example.

https://github.com/dancormier/react-native-swipeout/blob/master/example/SwipeoutExample.js

**Comment by mikeKane** [comment]
This is still an issue. Following the example 

```
 <Swipeout
        // autoClose={true}
        sensitivity={40}
        style={{ backgroundColor: "white" }}
        right={swipeoutBtns}
      >
        <TouchableWithoutFeedback onPress={() => this.selectResult(index)}>
        <View>
          <Results result={item} />
        </View>
        </TouchableWithoutFeedback>
      </Swipeout>
```
The view will not swipe if TouchableWithoutFeedback is present.
