### ISSUE TITLE
Will TypeScript definitions be released on npm?

### ISSUE THREAD

**Issue by lukecwilliams** [dancormier/react-native-swipeout#227]
For now we can copy the .d.ts file into our project, but longer term it would be nice to deploy the .d.ts file along with the npm project.  The most recent version on npm (2.2.2) does not include them.

Will they be deployed to npm?

Thanks!

**Comment by lukecwilliams** [comment]
Thanks!

**Comment by sytolk** [comment]
This fix open new issue: https://github.com/dancormier/react-native-swipeout/issues/230
