### ISSUE TITLE
Question: How do you call your own functions predefined functions from the SwipeoutButton?

### ISSUE THREAD

**Issue by MossP** [dancormier/react-native-swipeout#23]
Firstly, this is amazing!! I love it, thank you! (been wanting to say that for a few days).

My question..
I can see that you can add a function inline by:
```
var Swipeoutbuttuns = [
  {
    text: "MyButton",
    onPress: function(){ alert('button pressed') },
  }
]
```
but what if I have a function already?
e.g.
```
var rowData = {someData};

myFunction: function(data){
  // do something with data and ref "componentRef"
},

render: function(){
  var Swipeoutbuttuns = [
    {
      text: "MyButton",
      onPress: function(){ this.myFunction(rowData) },
    }
  ];

return (
  <Swipeout right={swipeoutbuttons} ref="componentRef">
    // my layout using rowData
  </Swipeout>
}
```

I considered passing in a custom component but figure that I'll have the same issues as I can't passProps to it either?

**Comment by dancormier** [comment]
Hello MossP,
I'm glad you're finding swipeout handy! I think I may have a solution to your problem...

The scope of `this` is changed when containing it within a function (basically, `this` references this function, not the component). You can tie `this` to a variable so you refence it within your onPress function. For example:

```
/// redefine "this" 
var self = this;


// note:  self.myFunction(rowData)
var Swipeoutbuttuns = [
  {
    text: "MyButton",
    onPress: function(){ self.myFunction(rowData) },
  }
];

```

**Comment by MossP** [comment]
Hi Dan.

Thanks for getting back to me. I hadn't thought of trying to assign a reference to "this" so that i could pass it down the chain. I'll try this out. Thank you :) and thanks again for the plugin :)

**Comment by dancormier** [comment]
My pleasure!

**Comment by MossP** [comment]
That worked great. Thank you :)
