### ISSUE TITLE
[Build Error] project didn't build

### ISSUE THREAD

**Issue by sqlProvider** [dancormier/react-native-swipeout#230]
Please check this error. 

[![image](https://i.hizliresim.com/yz36W7.png)](https://hizliresim.com/yz36W7)

**Comment by kozillla** [comment]
have the same issue

**Comment by vysotsky** [comment]
@kozillla thanks, it worked pretty cool for me! Can you please explain what's going wrong with it?

**Comment by hushicai** [comment]
.babelrc break something...

```
Couldn't find preset \"es2015\" 
```

**Comment by hironarita** [comment]
I'm also getting this issue.

**Comment by sytolk** [comment]
Remove ^ from version and fixed like that :)
`"react-native-swipeout": "2.2.2"`
the problem is in version 2.3.0 and commit: 
https://github.com/dancormier/react-native-swipeout/commit/f6d0fbce263197b2b3865cf2fc122c694ae07f41

**Comment by almirfilho** [comment]
__.babelrc__ file should not be shipped to NPM. I'm going to make a PR to fix this.

**Comment by jasdeepsingh** [comment]
have the same issue.

**Comment by silentcloud** [comment]
Fixed in 2.3.1
