### ISSUE TITLE
Use Fontawesome with Swipeout

### ISSUE THREAD

**Issue by Base29** [dancormier/react-native-swipeout#242]
Hello Guys ... I want to use Fontawesome Icons for the button text ... I have done this by installing a Fontawesome module and in the `text:` parameter of button options I passed the instance of the fontawesome module like this 

```
const swipeoutBtns = [
    {
        onPress: () => {
            console.log("Item Deleted");
        },
        text: <FontAwesome style={{fontSize: 26, color: '#FFFFFF'}}>{Icons.trash}</FontAwesome>,
        backgroundColor: '#DC0404'
    }
]
```

Though I have the icon there instead of text but I am getting  a warning shown in this screenshot http://prntscr.com/hknb7u ... how can I fix this ? is there a option that I can use ? Let me know ... Thanks

**Comment by nicolasbrugneaux** [comment]
Since the maintainer doesn't seem to want to help you, I can try to give you a piece of advice. 

You should use the `component` props, **not** the `text` props if you want to provide custom element.
