### ISSUE TITLE
Adding icon in swipelist instead of text

### ISSUE THREAD

**Issue by webdevsyd** [dancormier/react-native-swipeout#246]
Hi @dancormier 

I would like to ask if how can I add an icon in the swipe button, the design that was given to me uses an icon instead of text. Hope you can help me. Thank you!

**Comment by baraa95** [comment]
hey @webdevsyd 

you could do so like the following 

i am using **react-native-elements**  to get the **Icon** class 


```

swipeoutBtns : [
            {
                component:<Icon raised 
                color='white'
                containerStyle={{backgroundColor: '#FF5722'}}
                name='delete'/>,
                onPress:()=>this.setState({delete:true})
            }
]

```

**Comment by silentcloud** [comment]
@webdevsyd  https://github.com/dancormier/react-native-swipeout#button-props `component` prop
