### ISSUE TITLE
Not working with React Native 0.55.2

### ISSUE THREAD

**Issue by EyalSi** [dancormier/react-native-swipeout#262]
Seems like moving to react native 0.55.2 introduces a problem in swipeout on iOS.
When swiping on one of the directions, the view will not return completely leaving blank pixels, which will remain hidden grey even after closing the swipe. it gets larger when swiping again...
Returning to 0.54.4 fixes the problem ;) 

Anyone has a clue how to fix?
10x

**Comment by EyalSi** [comment]
Same problem in 0.55.3

**Comment by kevinscience** [comment]
Is there any help?

**Comment by sbkl** [comment]
Using 0.55.3. Made a test implementing my own PanResponder to get a similar behaviour to the swipeable component using an animated value pulling the list item to the left of the screen. Same issue. The image going out of the screen get the width shrinking when it get back on the screen.

**Comment by pinguinjkeke** [comment]
https://github.com/facebook/react-native/issues/19244

**Comment by ryanoboril** [comment]
It looks like the fix for this has been merged.
