### ISSUE TITLE
List View doesn't seem to have a property 'scrollEnabled'

### ISSUE THREAD

**Issue by evanmrose** [dancormier/react-native-swipeout#27]
When you set 
    scrollEnabled={this.state.scrollEnabled}

Looking at the RN docs and code, there doesnt seem to be any hook for a scrollEnabled property on a list view to lock scrolling. Am I missing something? Did you extend the ListView component?

**Comment by dancormier** [comment]
Hey @evanmrose,

I didn't extend ListView, but ListView extends ScrollView props by default: [React Native Docs - ListView](https://facebook.github.io/react-native/docs/listview.html#props)

Also, if you've haven't seen the wiki, I recommend it for some useful info relating to locking scroll. 
It explains how Swipeout prop `scroll ` returns false when swipeout is opening, which is then passed to a function that sets the state of `scrollEnabled`, allowing you to lock the scroll. [react-native-swipeout wiki: Scrolling](https://github.com/dancormier/react-native-swipeout/wiki/Scrolling)

**Comment by evanmrose** [comment]
Thanks for the quick response!

**Comment by dancormier** [comment]
My pleasure :+1:
