### ISSUE TITLE
onPress事件在FlatList加载完之后立刻执行，不应该是在按下按钮的时候吗？

### ISSUE THREAD

**Issue by cyixlq** [dancormier/react-native-swipeout#277]
我用swipeout组件嵌套在列表项最外层，当FlatList列表加载完成的时候，右侧隐藏按钮立刻执行了所有的onPress事件，如图：
![MusicItem Component](https://upload-images.jianshu.io/upload_images/8654767-839e638818b9f1bc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![App.js](https://upload-images.jianshu.io/upload_images/8654767-f01509343918020f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![console log](https://upload-images.jianshu.io/upload_images/8654767-c37e012700655d32.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by cyixlq** [comment]
OK, I know. It's settled.

**Comment by thtTNT** [comment]
You can't write like this.
You should write like this:
onPress={() => method()}
