### ISSUE TITLE
Why not release v2.3.4?

### ISSUE THREAD

**Issue by HunDunDM** [dancormier/react-native-swipeout#284]
v2.3.4 was released half a year ago, but NPM can only get v2.3.3.
v2.3.3 `openRight` not work well.

**Comment by HunDunDM** [comment]
`dist` is not updated, so using a gitHub source is also not a solution.

**Comment by HunDunDM** [comment]
#274 is an important PR to fix an error in react-native@0.55.*

**Comment by silentcloud** [comment]
v2.3.4 has been published, sorry about for this
