### ISSUE TITLE
NativeButton Warnings

### ISSUE THREAD

**Issue by martakielpinska** [dancormier/react-native-swipeout#285]
Hello,
I've been working with swipeout for a while now and I never had problems that occur now. 
My react native version is 0.55.4 

I'm getting two warnings:
![1](https://user-images.githubusercontent.com/40487563/43134102-31686870-8f41-11e8-85b7-16187bd4a8e2.PNG)
![2](https://user-images.githubusercontent.com/40487563/43134103-3181fd9e-8f41-11e8-967a-cf65632bde4d.PNG)

Here is the swipeout options that are being passed:
```
const swipeoutOptions = {
        backgroundColor: "white",
        autoClose: true,
        rowId: this.props.key,
        sectionId: 1,
        onClose: (secId, rowId, direction) => {
            this.setState({
                activeRowKey: null,
            })
        },
        onOpen: (secId, rowId, direction) => {
            this.setState({
                activeRowKey: this.props.key,
            })
        },
        right: 
        [
            {
                onPress : ()=>{},
                text: "Delete",
                underlayColor: 'rgba(0, 0, 0, 1, 0.6)',
                backgroundColor: "#e2371d",
            }
        ],
      
    }
```
I'm very sorry if it's only my problem and not an actual reason for opening an issue, but I have never run into those problems before. The swipeout works but I wish to know how to properly get rid of those warnings. Thank you in advance for any information you can give me

**Comment by astraeapark** [comment]
oh i have same problem even i don't use textStyle and background!

` const deleteButton = [
            {
                text: 'Delete',
                onPress : ()=>{console.log("deleteBtn")},
            },
        ];
`

**Comment by zhan4139** [comment]
+1

**Comment by projectpaperfree** [comment]
Happening for RN 0.55.4

**Comment by daniel031699** [comment]
I also have this problem,if any way to solve this problem???
--I just started learning English

**Comment by martakielpinska** [comment]
This issue got closed but will there be any fix?

**Comment by ryanhomer** [comment]
I no longer have this issue after installing version `2.3.6`.
