### ISSUE TITLE
update lastest version error

### ISSUE THREAD

**Issue by daniel031699** [dancormier/react-native-swipeout#291]
i update it from 2.3.4 to 2.3.5,but i fouund this error,i used the env is react-native 0.55.4 and react is 16.3.1 and use android 5.1

![image](https://user-images.githubusercontent.com/15700134/43934369-a24c0f72-9c81-11e8-97b4-8fcd1b779d2f.png)

**Comment by silentcloud** [comment]
Sorry about this, try version 2.3.6

**Comment by daniel031699** [comment]
tks
