### ISSUE TITLE
cannot access state 

### ISSUE THREAD

**Issue by miaoanbang** [dancormier/react-native-swipeout#293]
` <Swipeout
            onOpen={() => console.log(this.state)}
            onClose={() => console.log(this.state)}
            right={[
              {
                text: 'Delete',
                backgroundColor: 'red',
                onPress: () => {
                  console.log(this.state);
                },
              }
            ]}
          >`

I am unable to access my state using this way. I am unable to change state by click the button.

Any ideas or suggestions how I can access and trigger setState by clicking the button?

**Comment by empiteranga** [comment]
how do you do that, the same issue
