### ISSUE TITLE
Feature Request: onClose callback

### ISSUE THREAD

**Issue by nullfox** [dancormier/react-native-swipeout#32]
There is currently an onOpen callback - it would be handy if there were an onClose callback as the buttons/components I have maintain state that I'd like to reset between open/close cycles.

How difficult would this be to implement?

**Comment by dancormier** [comment]
I don't think that would be *too* difficult.

I can now understand a use case for an onClose callback and I received a similar suggestion in #24, so I'm considering building it out. 

Thanks for the suggestion. :+1:

**Comment by achang28** [comment]
+1

**Comment by coderdave** [comment]
+1

**Comment by tazmattaz** [comment]
There should be an feature to know if swiper is open or not?
Cause if this is already opened then we should prevent our default click from row.
If this is open then on first click this swiper will close and on second click our default functionality should be worked.

**Comment by dancormier** [comment]
Here's a *very* late update for everyone. I've implemented `onClose` in my branch **[dc-redux](https://github.com/dancormier/react-native-swipeout/tree/dc-redux)** and it will be available once I release the next major version.

**Comment by hufeng** [comment]
+ 1

**Comment by yuilsang** [comment]
+1

**Comment by ChangJoo-Park** [comment]
+1

**Comment by tendant** [comment]
+1, any update on when this might be released?

**Comment by sscaff1** [comment]
+1

**Comment by pvpshoot** [comment]
any progress?
