### ISSUE TITLE
Doesn't Work with TouchableHighlight

### ISSUE THREAD

**Issue by geirman** [dancormier/react-native-swipeout#33]
I may be approaching this wrong, but once I wrapped the row with Swipeout, the default click state attached to TouchableHIghlight (e.g. `this._getTrackedItems( aircraft)`) stopped triggering.

```javascript
      <TouchableHighlight
        underlayColor='white'
        onPress={() => { this._getTrackedItems( aircraft ) }}>
        <View>
          <Swipeout 
            right={swipeoutBtns}
            autoClose='true'
            backgroundColor= 'transparent'>
            <View style={styles.rowContainer}>
              <View style={styles.countContainer}> 
                <Text style={styles.count}>
                  {aircraft.ti_count} 
                </Text>
                <Text style={styles.countLabel}>
                  TI's
                </Text>
              </View>
              <View style={styles.aircraftContainer}>
                <Text style={styles.aircraft}> 
                  {aircraft.reg_number} 
                </Text>
                <Text style={styles.cacheLabel}>
                  last updated: July 18, 2015 at 2:35 PM
                </Text>
              </View>
            </View>
          </Swipeout>
          <Separator />
        </View>
      </TouchableHighlight>
```

**Comment by dancormier** [comment]
Hi @geirman,

I think I understand the issue. The `<Swipeout/>` component should wrap your `<TouchableHighlight/>` like this:

```
<View>
  <Swipeout 
    right={swipeoutBtns}
    autoClose='true'
    backgroundColor= 'transparent'>
    <TouchableHighlight
      underlayColor='white'
      onPress={() => { this._getTrackedItems( aircraft ) }}>
      <View style={styles.rowContainer}>
        ...
      </View>
    </TouchableHighlight>
  </Swipeout>
  <Separator />
</View>
```

This will allow your component to be both clickable and swipeable to reveal the buttons. This is because <Swipeout/> contains both your swipeable element and the buttons (which have their own `<TouchableHightlight/>`).

Hopefully this solves your issue :+1:

**Comment by geirman** [comment]
That did the trick! Thanks! And thank you for creating this component... it's awesome!

**Comment by dancormier** [comment]
My pleasure :)

**Comment by tomtang539** [comment]
Hi @dancormier, this appears to be an issue for me that just came up on ios9.2.1 (13d20).  I have my touchablehighlight nested within swipeout and when I press on the component, I get this message on xCode:

[tid:com.facebook.React.JavaScript] onOpen: -1 -1

Also running this on iPhone 6s, might have something to do with 3D Touch?

**Comment by ilyago** [comment]
does't work on device note5

**Comment by geirman** [comment]
@ilyago I think this is native functionality now. I was going to provide a link to the docs, but wasn't able to quickly find a reference. 🤡

**Comment by silentcloud** [comment]
try version 2.1.1
