### ISSUE TITLE
Allow RN version 0.8.0-rc.2 in package.json

### ISSUE THREAD

**Issue by leoasis** [dancormier/react-native-swipeout#34]
I've just tried this package and it works correctly with that version of RN, would you update the package json to support it and perhaps publish a new release?

**Comment by dancormier** [comment]
Hi @leoasis,

I only support react-native via npm (so no release candidates), but I just updated swipeout to use react-native@0.9.0. React-native@0.10.0-rc was recently released and I will update to that when it exits it's release-candidate phase.

**Comment by leoasis** [comment]
@dancormier awesome, thanks! I was planning on adding support for using directly the new animated API, instead of react-tween-state, for versions that support it. Here is a repo that handles supporting both IMO pretty elegantly: https://github.com/oblador/react-native-collapsible.
