### ISSUE TITLE
App won't build

### ISSUE THREAD

**Issue by wheycool** [dancormier/react-native-swipeout#35]
After installing react-native-swipeout to my functioning app, I get the following error from React-Native:

```"TransformError: /app/node_modules/react-native-swipeout/node_modules/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationContext.js: This transform does not support getter methods for ES6 classes. (line: 53, col: 2)."```

Any idea how I can remedy this? Thanks!

**Comment by achang28** [comment]
@wheycool:  Everytime I come across this issue, removing the ```react-native``` dependency from the ```node_modules``` folder of this library does the trick.  I believe having ```react-native``` included in this library is now widely accepted as the culprit for these initialization problems where the version of React Native > v0.6.0

**Comment by wheycool** [comment]
Thanks for the suggestion, @achang28. 

Commenting out react-native's dependency from the ```package.json``` file that exists within the ```react-native-swipeout``` directory doesn't seem to do the trick – I get the same error. Am I missing something?

**Comment by oblador** [comment]
`react-native` should be a `peerDependency`. 

@wheycool: You have to remove the react-native folder inside `node_modules/react-native-swipeout/node_modules` too.

**Comment by dancormier** [comment]
I've been away on holiday, but I will check into this soon and report back.

**Comment by dancormier** [comment]
I changed `react-native` to `peerDependency` per @oblador's advice, and closed the issue. If this issue persists, reopen the issue and I'll check it out.

Thanks for your patience everyone! :+1:
