### ISSUE TITLE
Component in Swipeout 

### ISSUE THREAD

**Issue by robtg4** [dancormier/react-native-swipeout#36]
It seems as though when I try to put a component within the swipeout right prop, nothing shows. Here's what I have so far:

![screen shot 2015-09-04 at 2 45 15 pm](https://cloud.githubusercontent.com/assets/13613075/9691920/98a13d68-5313-11e5-9cd7-3ffa9eacda6e.png)

Also, is there anyway to change the width of the Swipout view? Thanks!

**Comment by dancormier** [comment]
I think you need to pass `List` as a component to the `component` prop, like this:
```
var list = [
  {
    component: <List/>
  }
]
```

**Comment by dancormier** [comment]
And as far as changing the width of the swipeout view, I don't believe there is currently. I'm trying to get around to a version update and I'll consider including that.

**Comment by robtg4** [comment]
Ok perfect! Thanks - and yeah I think that'd be a great prop to include! Would really change the game in terms of how dynamic react native apps can be.
