### ISSUE TITLE
Can't change width for swipeout button component

### ISSUE THREAD

**Issue by yuriy-vorontsov** [dancormier/react-native-swipeout#42]
Hi, Dan!

There is a problem with using a label for swipeout component with a long word, such as "Unsubscribe". The label breaks in two lines. It happens because the the width is limited to 1/5 of Device width.
I've tried to use button component to use a custom View with fixed width, but it didn't fix the issue.

I see two ways to fix this problem:
1. Add a new optional property style to set just stylesheet (not the whole component).
2. Read style property from swipeout component and use style.width for container.

What do you think about it?

**Comment by wootwoot1234** [comment]
+1

I'm having the same issue.  I would love to have some way to change the width of the buttons.

**Comment by dancormier** [comment]
Hi Yuriy and woot,

I have an update. I'm currently writing [an update](https://github.com/dancormier/react-native-swipeout/tree/dc-redux) that should resolve this issue and allow for passing of custom style (including width) to buttons in swipeout.

**Comment by wootwoot1234** [comment]
@dancormier thanks for the update. Glad to see you're still working on this library, it's really useful. Thanks!

**Comment by yuriy-vorontsov** [comment]
@dancormier Great to hear it! Thank you!

**Comment by markrickert** [comment]
+1 My ListView isn't the entire width of the screen, so the default button width of `width/5` doesn't work. I need a way to explicitly set the button width, or even better: it automatically knows how wide a 1 button swipeout needs to be based on the button itself instead of as a function of the component's width.

**Comment by kesha-antonov** [comment]
Hello @dancormier !
Do you have time? Any progress on this?
I tried to figure out solution myself but not succeeded yet.

**Comment by kesha-antonov** [comment]
Agreed with @markrickert . Great if it would be set automatically.

**Comment by markrickert** [comment]
Also, wondering on the progress of the `dc-redux` branch, @dancormier. Should we be using that as base for pull requests or `master`?

**Comment by kesha-antonov** [comment]
<img width="312" alt="screen shot 2016-03-07 at 01 30 44" src="https://cloud.githubusercontent.com/assets/11584712/13557580/4a4b0ef0-e404-11e5-93b9-ba06727704d9.png">
I have some luck with that. With `flex: 1` in screenshot we have padding from right.
Without `flex: 1` we won't have effect of growing buttons

**Comment by kesha-antonov** [comment]
Here's code: https://github.com/kesha-antonov/react-native-swipeout
Hope it can help.

Just add `styleButton: { width: 90, backgroundColor: 'rgba(228, 178, 48, 1)' }` to `<Swipeout right={[...`

**Comment by kesha-antonov** [comment]
So guys if you're okay to use it without "growing" effect then you'll be able to set custom widths on right buttons with my fork at this rev: https://github.com/kesha-antonov/react-native-swipeout/tree/b717a0d6ce17699d260951e41b6b603d3b4c5949

**Comment by kesha-antonov** [comment]
<img width="217" alt="screen shot 2016-03-08 at 19 30 33" src="https://cloud.githubusercontent.com/assets/11584712/13608090/447e3ca2-e564-11e5-918e-cbb755e62174.png">

**Comment by jaewonch** [comment]
@kesha-antonov I am trying to get the row to be swiped all the way, so in order to increase the width of the button to cover the full row when swiped, just for testing, I tried `let rightButton = [{styleButton: { width: 100 }}]` and `<Swipeout right={rightButton} backgroundColor= 'transparent'>` but the button is not affected and has the default width. Is this correct way to do it? Is there a better approach?

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/pull/134
