### ISSUE TITLE
Incompatible with Android

### ISSUE THREAD

**Issue by MossP** [dancormier/react-native-swipeout#43]
Great plugin, thank you. Just a heads up that it's not compatible with Android.

```
  Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
```

React Native v0.14.2

**Comment by emhagman** [comment]
+1. Would love to use this on Android

**Comment by peterlazar1993** [comment]
+1 Eagerly waiting for Android Support.

**Comment by BigPun86** [comment]
:+1:  Need this too

**Comment by dancormier** [comment]
+1 ;)

Hi all,

I'm happy to hear there's enthusiasm to use swipeout on Android. I'm working on an update that includes Android compatibility. If you'd like to contribute, it's in the [dc-redux branch](https://github.com/dancormier/react-native-swipeout/tree/dc-redux).

**Comment by wvengen** [comment]
:+1: Good news, thanks!

**Comment by dancormier** [comment]
This should be resolved in https://github.com/dancormier/react-native-swipeout/commit/15ab71c6085e7c34c8f3de037ed09ebcf9d2ef92

If any issues occur, let me know!

**Comment by npomfret** [comment]
Is there a release that's compatible with android now?  I'm using ^2.0.12 and it's not working well.

**Comment by wvengen** [comment]
Currently using https://github.com/q-m/react-native-swipeout/tree/android-support
https://github.com/trippcr/react-native-swipeout/commit/ce2b048498c301d73c45c45d8ef5c36a2dba7840

**Comment by npomfret** [comment]
thanks.
