### ISSUE TITLE
Blocking child Touchable on iPhone 6s and 6s Plus

### ISSUE THREAD

**Issue by alexrabarts** [dancormier/react-native-swipeout#44]
There seems to be an issue with PanResponder and 3D touch on new iPhone devices. A TouchableHighlight inside a Swipeout component does not respond to its onPress handler. This issue has been raised in the react-native project (https://github.com/facebook/react-native/issues/3082) but could also be handled in react-native-swipeout by looking at the position of the child component (see https://github.com/facebook/react-native/issues/3082#issuecomment-144689910).

**Comment by mhollweck** [comment]
+1

**Comment by iwater** [comment]
+1

**Comment by dancormier** [comment]
Hi all,

Thanks for reporting this. I'll be working on a [major update](https://github.com/dancormier/react-native-swipeout/tree/dc-redux) this weekend, and I'll check out this issue and try implementing the fix described by @alexrabarts.

**Comment by dancormier** [comment]
Just merged PR #47 which should fix this issue. Thanks @mhollweck!
