### ISSUE TITLE
Elements of ListView become invisible after rerender in inactive page inside Navigator.

### ISSUE THREAD

**Issue by agolovenko** [dancormier/react-native-swipeout#45]
Hell of a bug=)
It started after moving to 0.14.2 from 0.13.1. 
1. MainScreen has a ListView with rows rendered to Swipeout nodes.
2. Pressing each node transfers Navigator to node's details page where you can trigger actions that change rows for MainScreen. 
3. Hence render is triggered on inactive MainScreen while still observing node's details page. 
4. Going back (popping Navigator's history) I observe MainScreen with invisible elements.

If I remove Swipeout the list becomes visible and updated properly after these actions. Also was working with Swipeout and 0.13.1

**Comment by iwater** [comment]
same issue as you

**Comment by iwater** [comment]
I fix this by disabled ListView removeClippedSubviews

**Comment by masom** [comment]
Thanks @iwater 

Disabling `removeClippedSubviews` is a good temporary fix until swipeout is updated.
