### ISSUE TITLE
OnOpen is triggered when swiping left or right

### ISSUE THREAD

**Issue by mhollweck** [dancormier/react-native-swipeout#46]
For my understanding, OnOpen should be triggered when the user clicks on the item itself and not when the user swipes left or right. However, OnOpen is being triggered whenever the user interacts with the component. Can you fix this? (Since TouchableHighlight is no alternative)

**Comment by dancormier** [comment]
Hi @mhollweck,

`onOpen` is used to pass a function to be run when the swipeout buttons are exposed. To trigger something on interacting with the item, you would add `onPress` to the item wrapped in swipeout.

```
<Swipeout onOpen={this.runsWhenButtonsAreExposed}>
  <TouchableHighlight onPress={this.runsWhenRowIsPressed}/>
</Swipeout>

```
