### ISSUE TITLE
react-tween-state pulls in react-dom + react

### ISSUE THREAD

**Issue by cancan101** [dancormier/react-native-swipeout#49]
The dependency on `react-tween-state` is causing these to be pulled in which is not desirable:

```
├── react-dom@0.14.3
├── react@0.14.3 (envify@3.4.0, fbjs@0.3.2)
```

**Comment by dancormier** [comment]
My next update in [dc-redux](https://github.com/dancormier/react-native-swipeout/tree/dc-redux) removes `react-tween-state`, so it should solve this issue :)

**Comment by wootwoot1234** [comment]
I'm getting warning about this too.  @dancormier, any updates on the next update?  I love this module, thanks for the great work!
