### ISSUE TITLE
Directional lock

### ISSUE THREAD

**Issue by oblador** [dancormier/react-native-swipeout#5]
When swiping left and not keeping it exactly on a line the parent `scrollView` will also scroll. That's a bit annoying and not how a native UITableView works. 

I've tried applying `directionalLockEnabled={true}` to it but I assume that only works for it's own pan handler.

**Comment by dancormier** [comment]
Added this as a todo in the readme. I'm guessing that swipeout will have to pass back some state to the parent ScrollView, but I'll look into simple options.

**Comment by dancormier** [comment]
Scroll locks with `scrollEnabled` on ListView. This should work the same for ScrollView, but I haven't test it yet. I plan to make a wiki explaining how to lock scroll on parent (detailed in #19).
