### ISSUE TITLE
Prevents onPress from Making it to Parent Container

### ISSUE THREAD

**Issue by cancan101** [dancormier/react-native-swipeout#51]
This does not work correctly since the onpress never makes it to the parent.
```jsx
      <Listitem
          onPress={() => {....;}}
          backgroundColor='#EEE' >
          <Swipeout right={swipeoutBtns} style={{backgroundColor: '#EEE'}}>
              ....
```

**Comment by dancormier** [comment]
This is because the `Listitem` element here should be contained *within* the `Swipeout` element. If I am misunderstanding the issue, please reopen this ticket and I will take a look.

**Comment by cancan101** [comment]
If I reorder the components, then the onPress works but the swipe to reveal no longer works.
