### ISSUE TITLE
setState on unmounted component?

### ISSUE THREAD

**Issue by aksonov** [dancormier/react-native-swipeout#52]
I'm getting this after i've deleted element, datasource was updated and component was re-rendered...

![simulator screen shot 10 2015 10 42 19](https://cloud.githubusercontent.com/assets/1321329/11712083/18359ae8-9f2b-11e5-9696-9156670810d9.png)
![simulator screen shot 10 2015 10 42 20](https://cloud.githubusercontent.com/assets/1321329/11712088/1ea512d2-9f2b-11e5-80bf-ee6785ed5d19.png)

**Comment by aksonov** [comment]
Solved it by using InteractionManager.runAfterInteractions, maybe you could mention it that onPress actions should be wrapped to avoid setting state on unmounted component during 'closing' cell..

**Comment by albertfdp** [comment]
@aksonov Can you give a small example on how would you do that using `InteractionManager.runAfterInteractions`? I'm having this same issue. Thank you

**Comment by JonathanZWhite** [comment]
@albertfdp so after a bit of experimenting with @aksonov's suggestion, the before and after code below shows how you use `InteractionManager.runAfterInteractions`.

Before I had code like this which was dispatching an `action` and causing the `setState` on a unmounted component warning.
```
onPress: () => {
  this.props.handleDeletePress(this.props.key)
}
```

By wrapping the function with InteractionManager's `runAfterInteraction` the warning should go away. 
```
onPress: () => {
  InteractionManager.runAfterInteractions(() => {
    this.props.handleDeletePress(this.props.key)
  });
}
```

Issue https://github.com/facebook/react-native/issues/2248 provides an example of how to use `InteractionManager.runAfterInteractions` if you need further examples.

**Comment by aaroncrawford** [comment]
@JonathanZWhite Thank you for this.  Ran into it and had no idea why it was happening.

**Comment by JonathanZWhite** [comment]
@aaroncrawford No problem. Glad I was able to help :100:

**Comment by jonathandion** [comment]
Thanks allot @JonathanZWhite. You save me allot of time.
