### ISSUE TITLE
slow performance both on iphone 6 and simulator

### ISSUE THREAD

**Issue by michalfeher** [dancormier/react-native-swipeout#53]
Hi,

I am experiencing slow performance (lagging) when I run your example code. Both on Xcode simulator and when built on Iphone 6. everything is up-to-date (xcode, ios).

any ideas? thanks.

**Comment by ahanriat** [comment]
@michalfeher I think it's because it uses TweenState instead of the React Native Animated Api ;)

**Comment by michalfeher** [comment]
@ahanriat thanks, could be. but building it with the dev flag set to false made it run 60fps :)

**Comment by ahanriat** [comment]
It's because it calls Javascript on each frame. When the dev flag is set to true, each time your component is re rendered (with TweenState), there is a lot of overhead (check of propTypes etc..). When using the Animated Api, you can offThread the animations, and update style without re render your component. So even with the dev flag set to true, it will run at 60fps ;)

**Comment by bsudekum** [comment]
I'm also seeing poor performance. It seems to happen the most after heavy scrolling. 
![3](https://cloud.githubusercontent.com/assets/1058624/12162662/005222e4-b4ba-11e5-9b05-2fde54cfd45e.gif)

This is with the dev flag set to true.

**Comment by ahanriat** [comment]
Whaooo that's rude ! You should try this branch https://github.com/dancormier/react-native-swipeout/tree/dc-redux, it use Animated Api :smile:

**Comment by bsudekum** [comment]
@ahanriat this is not a jab at you nor your code, simple an observation. I'll check out the branch.

**Comment by dancormier** [comment]
Hi @ahanriat, @bsudekum, @michalfeher,

The current master does use tween-state, which creates this laggy performance. The branch @ahanriat referenced is not yet ready for release, but it's almost done and it does use the RN Animated
 API. Hopefully, I can find some time to wrap it up and release this majorly updated version soon. All contributions are welcome!

**Comment by dancormier** [comment]
Also, for anyone wondering what's left for the next major update:

https://github.com/dancormier/react-native-swipeout/tree/dc-redux#to-do-for-v300-issues

**Comment by ahanriat** [comment]
Yeah sorry for the confusion, I just wanted to say that the animation was very very slow ;)
