### ISSUE TITLE
React-Native ListView render SwipeOut scroll conflict

### ISSUE THREAD

**Issue by hufeng** [dancormier/react-native-swipeout#59]

**Comment by zxyah** [comment]
@hufeng 
这问题我也发现了，为现在直接改成用scrollView了
大师自己写一个吧，我用你的

**Comment by hufeng** [comment]
@zxyah 我们解决了 :)

**Comment by zxyah** [comment]
擦，分享出来啊，
是不是在开始滑动的时候，把listView的scrollEnabled禁用掉，结束后再启用

**Comment by herbertdai** [comment]
@hufeng  How do you fix it?

**Comment by chujian** [comment]
我也遇到这个问题,楼上的能说下怎么解决的吗? 不能让listview滚动

**Comment by UrbanSam** [comment]
In the index.js, 
onShouldBlockNativeResponder: (event, gestureState) => false,
Set is to false, seem to work fine. I haven't test it on IOS yet, but it works on android.

**Comment by FunProject** [comment]
Thanks @UrbanSam, it works. There should be prop we can set, e.g. shouldBlockNativeResponder, default: true. But who need can set to false.
PS: I had problem on Android (iOS works OK) that I can't scroll in FlatList. That solved my problem.
