### ISSUE TITLE
Example gif in README

### ISSUE THREAD

**Issue by brentvatne** [dancormier/react-native-swipeout#6]
[licecap](http://www.cockos.com/licecap/) is a great way to capture gifs easily on your screen - it would be useful for people browsing this to get a quick look at how it works :smile:

**Comment by dancormier** [comment]
The people have spoken and a preview image has been added to the readme! :+1: 
![](http://i.imgur.com/YX1seKj.gif)

**Comment by brentvatne** [comment]
Awesome :smile: Nice one
