### ISSUE TITLE
Naming collision from packager

### ISSUE THREAD

**Issue by adamski** [dancormier/react-native-swipeout#65]
Running `npm start` after installing I get
`Error: Naming collision detected: /<path-to-app>/node_modules/react-native/node_modules/fbjs/lib/EventListener.js collides with /<path-to-app>/node_modules/react-native-swipeout/node_modules/react/node_modules/fbjs/lib/EventListener.js`

**Comment by masom** [comment]
@adamski This error is related to react + react-native itself. The packager is having a lot of issues since RN started being pulled from npm instead of being vendored.

See https://github.com/facebook/react-native/issues/5180

**Comment by ajwhite** [comment]
Same issue here

**Comment by Elyx0** [comment]
Upgrade react-native, upgrade npm to latest,upgrade node, clear npm cache, try recreating project from scracth in another folder. Had to do all that. Best of luck.

**Comment by JonathanZWhite** [comment]
I upgraded my npm version to 3.x.x and that seemed to resolve the issue

**Comment by adamski** [comment]
Yes this is now resolve for me.
