### ISSUE TITLE
Examples unclear on how to pass props to buttons

### ISSUE THREAD

**Issue by bfarrgaynor** [dancormier/react-native-swipeout#70]
How do you pass a custom property such as a 'row id' to an onPress function on your swipeoutBtns? Since these actions are meant to act on list items, this seems like an obvious need. However I can't find how you approach this in any of your examples? 

eg. 

`
onPress: function(id) {
    console.log('You clicked the button on row ' + id);
}
`

??

**Comment by bfarrgaynor** [comment]
Ok so I think I figured out an approach.

`
 
    renderRow: function(rowData) {
        
        
        let swipeoutBtns = [
              {
                text: 'Mark as read',
                onPress: () => { 
                       this.markAsRead(rowData);
                     },
              }
            ];
        
        
        
    return (
          <Swipeout autoClose={true} right={swipeoutBtns}>
     // ... rest of your row render function
`

**Comment by SteffenC** [comment]
@bfarrgaynor Could you share a bit more of your code ? I'm having the same issue, and can't quite see how this should work

**Comment by bfarrgaynor** [comment]
@SteffenC rather than calling a local function on the list component, I make each item it's own component.

In my main component (the list):
```
render: function() {

            return (
                <View style={gStyles.listViewMax}>
                    
                       <ListView
                        dataSource={this.state.dataSource}
                        renderRow={this.renderAlert}
                        style={gStyles.jobListView}
                      />
                   
                </View>
             );
},
 
renderAlert: function(job) {
        return (<AlertListItem alertKeyType={this.state.alertKeyType} job={job} />);
  },
```


My AlertListItem.js (Component)
```
 render: function() {
        
        var myButtons = null;
        
        if(this.state.read) {
                myButtons  = [
                      {
                        text: 'Mark as Unread',
                        backgroundColor: '#FCA612',
                        color:'white',
                        onPress: () => { 
                               this.markRead('markunread');
                             },
                      }
                    ];
         } else {
                myButtons = [
                      {
                        text: 'Mark as Read',
                        backgroundColor: '#FCA612',
                        color:'white',
                        onPress: () => { 
                               this.markRead('markread');
                             },
                      }
                    ];
             
         }

         let swipeoutBtns = myButtons;
    
        return (<Swipeout autoClose={true} job={this.props.job} right={swipeoutBtns}>
              <View style={gStyles.alertListViewItemContainer}>
                  <View style={gStyles.alertListViewItemContainerButton}>
                    
                          <View style={gStyles.alertListViewItemPersonalDetails}> 
                              <Text style={gStyles.alertListViewItemName}>{this.props.job.firstname} {this.props.job.lastname}</Text>
                              <Text style={gStyles.alertListViewItemNote}>{this.props.job.note}</Text>
                              <Text style={gStyles.alertListViewItemTimeAgo}>{this.props.job.datetime}</Text>
                          </View>
                      
                              
                          <View style={gStyles.alertListViewItemReadFlag}> 
                            {this.readOrNot()}
                          </View>
                  </View>
              </View>
        </Swipeout>);

```


... in this way I can use the props or the state on the component to store anything I want about that particular list item.

**Comment by SteffenC** [comment]
@bfarrgaynor Beautiful ! Thank you very much!

**Comment by rsp8055** [comment]
How to pass the onPress function as a prop to the custom component, here I tried some but not working 
` right: [
                {
                    onPress() {

                        const deletingRow = this.state.activeRowKey;
                        const jsonData = this.state.jsonData;

                        Alert.alert(
                            'Delete',
                            'Are you sure you want to delete ?',
                            [
                                { text: 'No', onPress: () => console.log('Cancel Pressed'), style: 'cancel' },
                                {
                                    text: 'Yes', onPress: () => {
                                        jsonData.splice(this.props.index, 1);
                                        this.props.parentFlatList.refreshFlatList(deletingRow);
                                    }
                                },
                            ],
                            { cancelable: true }
                        );

                    },

                    component: <SwipeDelete onPressFun={onPress()} />     // here to pass above onPress() ?
                }
            ],
`

**Comment by rsp8055** [comment]
It's so simple, the solution is here

` right: [
                {
                    onPress: () => {

                        const deletingRow = this.state.activeRowKey;
                        const jsonData = this.state.jsonData;

                        Alert.alert(
                            'Delete',
                            'Are you sure you want to delete ?',
                            [
                                { text: 'No', onPress: () => console.log('Cancel Pressed'), style: 'cancel' },
                                {
                                    text: 'Yes', onPress: () => {
                                        jsonData.splice(this.props.index, 1);
                                        this.props.parentFlatList.refreshFlatList(deletingRow);
                                    }
                                },
                            ],
                            { cancelable: true }
                        );

                    },
                    component: <SwipeDelete />,
                },
            ],`

**Comment by mangleshyadav** [comment]
@rsp8055  
could you please create a demo for the same on https://expo.io/snacks/

**Comment by rsp8055** [comment]
Here you can find out the example : https://www.youtube.com/watch?v=9qof4eCt9UY
