### ISSUE TITLE
npm WARN EPEERINVALID react-tween-state@0.1.4 requires a peer of react-dom@^0.14.2 but none was installed.

### ISSUE THREAD

**Issue by markrickert** [dancormier/react-native-swipeout#73]
I'm fairly new to React Native so I don't understand this message and if I should be concerned:

I do `npm install --save react-native-swipeout` in my project directory and get this:

`npm WARN EPEERINVALID react-tween-state@0.1.4 requires a peer of react-dom@^0.14.2 but none was installed.`

**Comment by kesha-antonov** [comment]
Hello!
ReactJS needs this. (react-tween-state requires it as a peer dependency)
But since you're using react-native I guess you're (and me :)) doesn't need to do `npm install react-dom --save`

**Comment by kesha-antonov** [comment]
https://github.com/chenglou/react-tween-state/blob/master/package.json#L41

**Comment by kesha-antonov** [comment]
It should work fine without `react-dom`.
