### ISSUE TITLE
swipe prevent content button event 

### ISSUE THREAD

**Issue by bluesky0109** [dancormier/react-native-swipeout#80]
<Swipeout backgroundColor={Util.colors.white} right={swipeoutBtns} autoClose={true} key={`${rowID}_${i}`}>
          <TouchableHighlight onPress={() => this._toGoodsDetailPage(item)}>
            <View>
              <View style={styles.rowContainer}>
                <TouchableHighlight style={{padding:10, alignSelf: 'center'}} onPress={() => {this._toggleCheckbox(rowID, i);}} underlayColor={Util.colors.white}>
                  <Image style={styles.checkbox} resizeMode={Image.resizeMode.cover} source={{uri: this._renderCheckbox(rowID, i)}} />
                </TouchableHighlight>
                <Image
                  style={styles.thumbnail}
                  resizeMode={Image.resizeMode.cover}
                  source={{uri: item.productImg}}
                  defaultSource={{uri: 'placeholders'}}
                />
                <View style={{flex:1}}>
                  <Text style={styles.productName} numberOfLines={1}>{item.productName}</Text>
                  <View style={{flex: 1, marginTop: 10}}>
                    <Text numberOfLines={2} style={styles.productSpecs}>{item.productSpecs}</Text>
                  </View>
                  <View style={{flexDirection: 'row', alignItems: 'flex-end'}}>
                    <Text style={styles.productPrice}>￥{item.productPrice}</Text>
                    <View style={styles.operator}>
                      <TouchableOpacity style={{paddingVertical:5,paddingLeft:5}} onPress={() => {this._decrement(rowID, i);}}>
                        <View style={styles.minusBtn}>
                          <Text style={styles.minus}>-</Text>
                        </View>
                      </TouchableOpacity>
                      <View style={styles.productNumView}>
                        <Text style={styles.productNum}>{item.productNum}</Text>
                      </View>
                      <TouchableOpacity style={{paddingVertical:5,paddingRight:5}} onPress={() => {this._increment(rowID, i);}}>
                        <View style={styles.plusBtn}>
                          <Text style={styles.plus}>+</Text>
                        </View>
                      </TouchableOpacity>
                    </View>
                  </View>
                </View>
              </View>
              {_lineView}
            </View>
          </TouchableHighlight>
        </Swipeout>

![26a82018-bc86-4347-a4a7-8c454b79401d](https://cloud.githubusercontent.com/assets/8929364/14057939/8395885c-f34a-11e5-8eb2-27f918109261.png)

can not easy click button

**Comment by silentcloud** [comment]
This has been fixed in version 2.0.13

https://github.com/dancormier/react-native-swipeout/commit/76ba2392fac6a0b0905a4309680f2beccf19f79d
