### ISSUE TITLE
onClose callback

### ISSUE THREAD

**Issue by yapcheahshen** [dancormier/react-native-swipeout#87]
please add

this.props.onClose(this.props.sectionID,this.props.rowID);

after this._tweenContent('contentPos',0);
this.setState({contentPos:0, openedLeft:false,openRight:false});

in _handlePanResponderEnd

so that parent element knows when a swipe is closed.

**Comment by sscaff1** [comment]
This would be very helpful.

**Comment by coderdave** [comment]
duplicate of https://github.com/dancormier/react-native-swipeout/issues/32 ?

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/commit/76ba2392fac6a0b0905a4309680f2beccf19f79d
