### ISSUE TITLE
(IOS) works great on simulator, but hard to swipe on iPhone

### ISSUE THREAD

**Issue by MichaelKonnerup** [dancormier/react-native-swipeout#88]
As the title says the swipe works poorly on iPhone. It is more sensitive for scrolling horizontal than swiping an item. Have compared it with several apps (Mail, Spotify) which works perfectly. Hope there is some kind of solution for this?

**Comment by teebolt** [comment]
+1

**Comment by magrinj** [comment]
I don't really know if it's your question, but you can disable the scroll of the ListView when you toggle swipeout buttons, by using the `scroll` props.

**Comment by lvcmenezes** [comment]
Why is this closed? Did you guys find a solution for this?
