### ISSUE TITLE
wouldn't we want to use the react native Animated api instead of tweenState?

### ISSUE THREAD

**Issue by faceyspacey** [dancormier/react-native-swipeout#90]
TweenState doesn't access native libraries directly, but rather calls `setState` on `requestAnimationFrame`.  It would be a lot smoother if we rewrote it to use the Animated API. Thoughts?

**Comment by latusaki** [comment]
https://github.com/dancormier/react-native-swipeout/tree/dc-redux

**Comment by silentcloud** [comment]
#93
