### ISSUE TITLE
What's the best way to make the entire row clickable?

### ISSUE THREAD

**Issue by braco** [dancormier/react-native-swipeout#97]
Everything I'm trying presents strange behaviors. TouchableOpacity inside of Swipeout steals drag movement after press, etc.

After opening the button tray, the first click would ideally collapse the buttons again.

Seems like this should be in the core component, no?

Would be a good opportunity to add other behavior, like onLongPress to expose buttons

**Comment by adamski** [comment]
I'm also struggling a little with large items in rows stealing mouse events. Any workarounds?

**Comment by cupofjoakim** [comment]
In the same situation here. The row should ideally have a prop for 'onPress', imo.

**Comment by minzhitang** [comment]
same problem，agree with @cupofjoakim

**Comment by fourteen** [comment]
+1

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/commit/76ba2392fac6a0b0905a4309680f2beccf19f79d

This has been fixed in version 2.0.13
